[menu]
executable = "wofi"
args = [
    "--show=dmenu",
    "--define=layer=overlay",
    "--allow-markup",
    "--allow-images",
    "--insensitive",
    "--cache-file=/dev/null",
    "--parse-search",
    "--height=40%",
    "--prompt={prompt}",
    "--conf=.config/wofi/config-catppuccin",
    "--style=.config/wofi/style/catppuccin-mocha.css",
]

[format]
output_format = '{indent}<b>Output {name}</b>    <span alpha="20000">({id})</span>'
workspace_format = '{indent}<b>Workspace {name} [{layout}]</b> on output {output_name}    <span alpha="20000">({id})</span>'
container_format = '{indent}<b>Container [{layout}]</b> <i>{marks}</i> on workspace {workspace_name}    <span alpha="20000">({id})</span>'
window_format = '{workspace_name}:img:{app_icon}:text:{indent} {urgency_start}<b>“{title:{:.60}...}”</b>{urgency_end}  —  <i>{app_name}</i> <i>{marks}</i>      <span alpha="20000">({output_name})</span>'
indent = "    "
urgency_start = '<span background="darkred" foreground="yellow">'
urgency_end = "</span>"
html_escape = true
icon_dirs = [
    "/usr/share/icons/hicolor/scalable/apps",
    "/usr/share/icons/hicolor/128x128/apps",
    "/usr/share/icons/hicolor/64x64/apps",
    "/usr/share/icons/hicolor/48x48/apps",
    "/usr/share/icons/Adwaita/64x64/apps",
    "/usr/share/icons/Adwaita/48x48/apps",
    "/usr/share/pixmaps",
]

[layout]
auto_tile = false
auto_tile_min_window_width_per_output_width = [
    [
        800,
        400,
    ],
    [
        1024,
        500,
    ],
    [
        1280,
        600,
    ],
    [
        1400,
        680,
    ],
    [
        1440,
        700,
    ],
    [
        1600,
        780,
    ],
    [
        1680,
        780,
    ],
    [
        1920,
        920,
    ],
    [
        2048,
        980,
    ],
    [
        2560,
        1000,
    ],
    [
        3440,
        1200,
    ],
    [
        3840,
        1280,
    ],
    [
        4096,
        1400,
    ],
    [
        4480,
        1600,
    ],
    [
        7680,
        2400,
    ],
]

[focus]
lockin_delay = 750

[misc]
seq_inhibit = false

[swaymsg_commands]
include_predefined = true
